spring.application.name=Backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=arpit123

#spring.datasource.url=jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q
#spring.datasource.username=interest_m17q_user
#spring.datasource.password=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu

spring.datasource.url=jdbc:postgresql://dpg-d44t2824d50c73epfmn0-a.singapore-postgres.render.com:5432/interest_tl5q
spring.datasource.username=interest_tl5q_user
spring.datasource.password=iwyrLhWHfLblsTwnAyZfkDDbUJZqlCHl
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q

#PGPASSWORD=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu psql -h dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com -U interest_m17q_user interest_m17q