spring.application.name=Backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=arpit123

#spring.datasource.url=jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q
#spring.datasource.username=interest_m17q_user
#spring.datasource.password=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu

spring.datasource.url=jdbc:postgresql://dpg-d6lvau9aae7s73f8b2pg-a.singapore-postgres.render.com:5432/interest_0og0
spring.datasource.username=interest_0og0_user
spring.datasource.password=V6cxkn0LS1ftMS5zi9PsztOmR7oggsZp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q

#PGPASSWORD=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu psql -h dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com -U interest_m17q_user interest_m17q