spring.application.name=Backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=arpit123

#spring.datasource.url=jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q
#spring.datasource.username=interest_m17q_user
#spring.datasource.password=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu

spring.datasource.url=jdbc:postgresql://dpg-d51u9e6mcj7s73ekqqkg-a.singapore-postgres.render.com:5432/interest_ioz7
spring.datasource.username=interest_ioz7_user
spring.datasource.password=OnmatuobKKZ1KuESqWPGo7VmbYInZC4q
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver

#jdbc:postgresql://dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com:5432/interest_m17q

#PGPASSWORD=DT3Lk8pseMrt4RUzbnTi777xWAHdXcUu psql -h dpg-d09kf415pdvs73drnr6g-a.singapore-postgres.render.com -U interest_m17q_user interest_m17q