spring.application.name=Backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=arpit123


spring.datasource.url=jdbc:postgresql://dpg-d6lvau9aae7s73f8b2pg-a.singapore-postgres.render.com:5432/interest_0og0
spring.datasource.username=interest_0og0_user
spring.datasource.password=V6cxkn0LS1ftMS5zi9PsztOmR7oggsZp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.app.jwtSecret=mySuperSecretKeyForJwtAuthenticationBackendApplication123
spring.app.jwtExpirationMs=3600000
